version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.hostname == manager1

  config:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
    image: sqshq/piggymetrics-config
    ports:
      - 8888:8888
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.hostname == manager2

  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
    image: sqshq/piggymetrics-registry
    depends_on:
      - config
    ports:
      - 8761:8761
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.hostname == manager3

  gateway:
     environment:
       CONFIG_SERVICE_PASSWORD: 'password'
     image: sqshq/piggymetrics-gateway
     depends_on:
       - config
     ports:
       - 8080:4000
     deploy:
       placement:
         constraints:
           - node.role == worker

  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
      NOTIFICATION_SERVICE_PASSWORD: 'password'
      STATISTICS_SERVICE_PASSWORD: 'password'
      ACCOUNT_SERVICE_PASSWORD: 'password'
      MONGODB_PASSWORD: 'password'
    image: sqshq/piggymetrics-auth-service
    depends_on:
       - config
    deploy:
      placement:
        constraints:
          - node.role == worker

  auth-mongodb:
    environment:
      MONGODB_PASSWORD: 'password'
    image: sqshq/piggymetrics-mongodb
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.hostname == manager1

  account-service:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
      ACCOUNT_SERVICE_PASSWORD: 'password'
      MONGODB_PASSWORD: 'password'
    image: sqshq/piggymetrics-account-service
    depends_on:
       - config
    deploy:
      placement:
        constraints:
          - node.role == worker

  account-mongodb:
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD: 'password'
    image: sqshq/piggymetrics-mongodb
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.hostname == manager3

  statistics-service:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
      MONGODB_PASSWORD: 'password'
      STATISTICS_SERVICE_PASSWORD: 'password'
    image: sqshq/piggymetrics-statistics-service
    depends_on:
       - config
    deploy:
      placement:
        constraints:
          - node.role == worker

  statistics-mongodb:
    environment:
      MONGODB_PASSWORD: 'password'
    image: sqshq/piggymetrics-mongodb
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.hostname == manager1

  notification-service:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
      MONGODB_PASSWORD: 'password'
      NOTIFICATION_SERVICE_PASSWORD: 'password'
    image: sqshq/piggymetrics-notification-service
    depends_on:
       - config
    deploy:
      placement:
        constraints:
          - node.role == worker

  notification-mongodb:
    image: sqshq/piggymetrics-mongodb
    environment:
      MONGODB_PASSWORD: 'password'
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.hostname == manager3

  monitoring:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
    image: sqshq/piggymetrics-monitoring
    depends_on:
      - config
    ports:
      - 9000:8080
      - 8989:8989
    deploy:
      placement:
        constraints:
          - node.role == worker
