version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672

  config:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
    image: sqshq/piggymetrics-config
    ports:
      - 8888:8888

  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
    image: sqshq/piggymetrics-registry
    depends_on:
      - config
    ports:
      - 8761:8761

  gateway:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
    image: sqshq/piggymetrics-gateway
    depends_on:
      - config
    ports:
      - 8080:4000

  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
      NOTIFICATION_SERVICE_PASSWORD: 'password'
      STATISTICS_SERVICE_PASSWORD: 'password'
      ACCOUNT_SERVICE_PASSWORD: 'password'
      MONGODB_PASSWORD: 'password'
    image: sqshq/piggymetrics-auth-service
    depends_on:
      - config

  auth-mongodb:
    environment:
      MONGODB_PASSWORD: 'password'
    image: sqshq/piggymetrics-mongodb

  account-service:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
      ACCOUNT_SERVICE_PASSWORD: 'password'
      MONGODB_PASSWORD: 'password'
    image: sqshq/piggymetrics-account-service
    depends_on:
      - config:

  account-mongodb:
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD: 'password'
    image: sqshq/piggymetrics-mongodb

  monitoring:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
    image: sqshq/piggymetrics-monitoring
    depends_on:
      - config
    ports:
      - 9000:8080
      - 8989:8989