version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    

  config:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
    image: sqshq/piggymetrics-config
    ports:
      - 8888:8888
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    

  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
    image: sqshq/piggymetrics-registry
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    

  gateway:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
    image: sqshq/piggymetrics-gateway
    ports:
      - 8080:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    

  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
      NOTIFICATION_SERVICE_PASSWORD: 'password'
      STATISTICS_SERVICE_PASSWORD: 'password'
      ACCOUNT_SERVICE_PASSWORD: 'password'
      MONGODB_PASSWORD: 'password'
    image: sqshq/piggymetrics-auth-service
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    

  auth-mongodb:
    environment:
      MONGODB_PASSWORD: 'password'
    image: sqshq/piggymetrics-mongodb
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    

  account-service:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
      ACCOUNT_SERVICE_PASSWORD: 'password'
      MONGODB_PASSWORD: 'password'
    image: sqshq/piggymetrics-account-service
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    

  account-mongodb:
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD: 'password'
    image: sqshq/piggymetrics-mongodb
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    

  statistics-service:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
      MONGODB_PASSWORD: 'password'
      STATISTICS_SERVICE_PASSWORD: 'password'
    image: sqshq/piggymetrics-statistics-service
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    

  statistics-mongodb:
    environment:
      MONGODB_PASSWORD: 'password'
    image: sqshq/piggymetrics-mongodb
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    

  notification-service:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
      MONGODB_PASSWORD: 'password'
      NOTIFICATION_SERVICE_PASSWORD: 'password'
    image: sqshq/piggymetrics-notification-service
    
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    

  notification-mongodb:
    image: sqshq/piggymetrics-mongodb
    environment:
      MONGODB_PASSWORD: 'password'
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    

  monitoring:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
    image: sqshq/piggymetrics-monitoring
    ports:
      - 9000:8080
      - 8989:8989
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    
