version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.hostname == manager1

  config:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
    image: sqshq/piggymetrics-config
    ports:
      - 8888:8888
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.hostname == manager2

   registry:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
    image: sqshq/piggymetrics-registry
    depends_on:
      - config
    ports:
      - 8761:8761
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.hostname == manager3

  gateway:
     environment:
       CONFIG_SERVICE_PASSWORD: 'password'
     image: sqshq/piggymetrics-gateway
     depends_on:
       - config
     ports:
       - 8080:4000
     deploy:
       placement:
         constraints:
           - node.role == worker

  monitoring:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
    image: sqshq/piggymetrics-monitoring
    depends_on:
      - config
    ports:
      - 9000:8080
      - 8989:8989
    deploy:
      placement:
        constraints:
          - node.role == worker
