version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672

  config:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
    image: sqshq/piggymetrics-config
    ports:
      - 8888:8888

  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
    image: sqshq/piggymetrics-registry
    ports:
      - 8761:8761

  gateway:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
    image: sqshq/piggymetrics-gateway
    ports:
      - 8080:4000

  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
      NOTIFICATION_SERVICE_PASSWORD: 'password'
      STATISTICS_SERVICE_PASSWORD: 'password'
      ACCOUNT_SERVICE_PASSWORD: 'password'
      MONGODB_PASSWORD: 'password'
    image: sqshq/piggymetrics-auth-service

  auth-mongodb:
    environment:
      MONGODB_PASSWORD: 'password'
    image: sqshq/piggymetrics-mongodb

  account-service:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
      ACCOUNT_SERVICE_PASSWORD: 'password'
      MONGODB_PASSWORD: 'password'
    image: sqshq/piggymetrics-account-service

  account-mongodb:
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD: 'password'
    image: sqshq/piggymetrics-mongodb

  statistics-service:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
      MONGODB_PASSWORD: 'password'
      STATISTICS_SERVICE_PASSWORD: 'password'
    image: sqshq/piggymetrics-statistics-service

  statistics-mongodb:
    environment:
      MONGODB_PASSWORD: 'password'
    image: sqshq/piggymetrics-mongodb

  notification-service:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
      MONGODB_PASSWORD: 'password'
      NOTIFICATION_SERVICE_PASSWORD: 'password'
    image: sqshq/piggymetrics-notification-service


  notification-mongodb:
    image: sqshq/piggymetrics-mongodb
    environment:
      MONGODB_PASSWORD: 'password'

  monitoring:
    environment:
      CONFIG_SERVICE_PASSWORD: 'password'
    image: sqshq/piggymetrics-monitoring
    ports:
      - 9000:8080
      - 8989:8989
